version: "3.8"

services:
  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: emsp-mysql
    environment:
      MYSQL_ROOT_PASSWORD: emsp123456
      MYSQL_DATABASE: emsp
      MYSQL_USER: emsp
      MYSQL_PASSWORD: emsp123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - emsp-network

  # Redis缓存
  redis:
    image: redis:7-alpine
    container_name: emsp-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - emsp-network

  # Eureka注册中心
  eureka:
    image: emsp/eureka:latest
    container_name: emsp-eureka
    ports:
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - emsp-network

  # API网关
  gateway:
    image: emsp/gateway:latest
    container_name: emsp-gateway
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka:8761/eureka/
    depends_on:
      - eureka
    networks:
      - emsp-network

  # 认证服务
  auth-service:
    image: emsp/auth-service:latest
    container_name: emsp-auth-service
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/emsp
      SPRING_DATASOURCE_USERNAME: emsp
      SPRING_DATASOURCE_PASSWORD: emsp123456
    depends_on:
      - mysql
      - eureka
    networks:
      - emsp-network

  # 用户服务
  user-service:
    image: emsp/user-service:latest
    container_name: emsp-user-service
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/emsp
      SPRING_DATASOURCE_USERNAME: emsp
      SPRING_DATASOURCE_PASSWORD: emsp123456
    depends_on:
      - mysql
      - eureka
    networks:
      - emsp-network

  # 商品服务
  product-service:
    image: emsp/product-service:latest
    container_name: emsp-product-service
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/emsp
      SPRING_DATASOURCE_USERNAME: emsp
      SPRING_DATASOURCE_PASSWORD: emsp123456
    depends_on:
      - mysql
      - eureka
    networks:
      - emsp-network

  # 订单服务
  order-service:
    image: emsp/order-service:latest
    container_name: emsp-order-service
    ports:
      - "8084:8084"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/emsp
      SPRING_DATASOURCE_USERNAME: emsp
      SPRING_DATASOURCE_PASSWORD: emsp123456
    depends_on:
      - mysql
      - eureka
    networks:
      - emsp-network

  # 动态服务
  moment-service:
    image: emsp/moment-service:latest
    container_name: emsp-moment-service
    ports:
      - "8085:8085"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/emsp
      SPRING_DATASOURCE_USERNAME: emsp
      SPRING_DATASOURCE_PASSWORD: emsp123456
    depends_on:
      - mysql
      - eureka
    networks:
      - emsp-network

volumes:
  mysql_data:
  redis_data:

networks:
  emsp-network:
    driver: bridge
